services:
  mongodb:
    image: mongo:7.0
    container_name: mongodb_nosql
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: ecommerce

volumes:
  mongo_data: